name: Create
# concurrency:
#  group: ${{ github.workflow }}-${{ github.event.ref }}
#  cancel-in-progress: false
on:
  workflow_call:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT }}
      - name: Change and Commit
        run: |
          echo "Using Branch: ${{ github.event.ref }}"
          #          bash push.sh
